### ISSUE TITLE
"Quit Launcher" doesn't work in some cases

### ISSUE THREAD

**Issue by PoohVz** [planetarium/9c-launcher#1001]
There are some reports about can't quit the game using the `Quit Launcher` option under the taskbar.
Restart works but not Quit
This only happens to some people.

**Comment by BasixKOR** [comment]
I've been looking about this but I couldn't find a reliable way to reproduce this nor the cause of this. I wish #1050 could help diagnose this issue so we could work on a fix.

**Comment by longfin** [comment]
@PoohVz Is it still occurring?

**Comment by PoohVz** [comment]
I don't see any new reports so far, so I assume it's fixed

**Comment by BasixKOR** [comment]
So actually this issue still persists, and it should be (really) fixed by #1181.
