### ISSUE TITLE
[Monster Collection] Cannot edit in specific flow.

### ISSUE THREAD

**Issue by boscohyun** [planetarium/9c-launcher#1088]
# Replay

1. Open the Monster Collection UI.
2. I have 4 monsters.
3. Decrease 1 monster and success with 3 monsters remained.
4. Do not close the Monster Collection UI.
5. Increase 1 monster and failed with some message modal.

If you close the Monster Collection UI in step 4, and step 5 worked fine.

**Comment by BasixKOR** [comment]
Closing as the legacy monster collection isn't maintained.
