### ISSUE TITLE
ci(circleci): upload artifact to AWS S3

### ISSUE THREAD

**Issue by moreal** [planetarium/9c-launcher#1099]
Currently, CircleCI and GitHub Actions' workflows upload their artifacts to their own artifact storage. So it has a different URL endpoint and it affects other programs dependent on the artifacts (e.g. move to CircleCI from GitHub Actions or something). So, in my thought, it will be better to upload them to AWS S3 to make them able to be accessed in the static endpoint. (e.g. `9c-artifacts.nine-chronciles.com/<COMMIT-SHA>`). Already planetarium/NineChronicles project also does that.

**Comment by moreal** [comment]
Sadly, circleci/aws-cli orb doesn't support Windows 😢 
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/26626194/145180304-28e5ef0a-f289-4e56-ab88-44744a65ae38.png">

**Comment by BasixKOR** [comment]
We could download from AWS directly like this: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html. Although this would increase our build time...

**Comment by moreal** [comment]
Thanks for letting me know it. 😀 I'm trying to install the AWS CLI with it.
