### ISSUE TITLE
Navigate to error page when there is no available remote nodes

### ISSUE THREAD

**Issue by moreal** [planetarium/9c-launcher#1112]
## Reproduction

Set `config.json`'s `RemoteNodeList` to empty list(`[]`). Then it will show error logs, `TypeError: Cannot read property 'HeadlessUrl' of undefined`.

**Comment by BasixKOR** [comment]
https://github.com/planetarium/9c-launcher/blob/development/src/config.ts#L337

**Comment by BasixKOR** [comment]
The fix has been merged.
