### ISSUE TITLE
Launcher does not load the NCG and block info for specific accounts

### ISSUE THREAD

**Issue by area363** [planetarium/9c-launcher#1117]
![launcher_error](https://user-images.githubusercontent.com/42176649/146301191-a233886c-4031-4cff-89a8-b405bd3b5d1c.png)

As pointed out in the screenshot above, the launcher doesn't load the NCG amount and block info for specific accounts. This feature `always works` for certain accounts but `always fails` for others.

@ipdae has pointed out that the accounts that always fail might have to do with those that don't use `MonsterCollection`.

**Comment by area363** [comment]
![sendncg_correct](https://user-images.githubusercontent.com/42176649/146305383-c16303f6-9160-4491-8501-b102a485c9c6.png)

BTW, the `Send NCG` page renders the correct amount.

**Comment by BasixKOR** [comment]
Currently the NCG balance is rendered by `monsterCollectionStatus` query. I think we could replace it with `GetNCGBalance` quite simply, although I'm unsure why `monsterCollectionStatus` was used...

**Comment by ipdae** [comment]
this is failed to get `MonsterCollectionStatus` information when account never used `MonsterCollection`.

**Comment by BasixKOR** [comment]
Reopening the issue since the patch above doesn't fully resolve the issue (the NCG amount will not be updated).
