### ISSUE TITLE
설치 파일로 배포

### ISSUE THREAD

**Issue by moreal** [planetarium/9c-launcher#118]
[Electron]에서 제공하는 [autoUpdater]를 사용하려면 [Squirell를 필요로 해서 설치되어 있는 어플리케이션에서만 동작한다고 합니다][need-squirell]. autoUpdater를 적용하려는 목적이 아니더라도 설치파일로 배포는 필요하니 찾아보면 좋을 것 같습니다.

## Windows

https://github.com/electron/windows-installer

[Electron]: https://www.electronjs.org/
[autoUpdater]: https://www.electronjs.org/docs/api/auto-updater#autoupdater
[need-squirell]: https://github.com/planetarium/9c-launcher/pull/115#issuecomment-653903173

**Comment by Akamig** [comment]
Um... we might use Squirrel in near future, but unlikely due to our update scheme, so marking as stale and closing this issue.
