### ISSUE TITLE
New release update only works after restarting the launcher in RPC mode

### ISSUE THREAD

**Issue by area363** [planetarium/9c-launcher#1207]
When playing in RPC mode, the launcher is updated to a new version only when you restart it.
But interestingly, you can still log in with the old version after the mainnet version update and the game works as well.
Currently, we've noticed that most RPC players don't restart their launcher unless absolutely necessary so this might be an issue when game actions are updated in the new release.

**<Playing in v100101 after v100102 release(RPC mode)>**
![image](https://user-images.githubusercontent.com/42176649/153539130-22a250b8-fe9c-435f-bd5a-fc62fb0c13b6.png)

**Comment by longfin** [comment]
Duplicate #1260
