### ISSUE TITLE
메인 프로세스 ipc 부분 리팩토링하기

### ISSUE THREAD

**Issue by riemannulus** [planetarium/9c-launcher#147]
현재 메인 프로세스의 IPC 등록 부분이 별개의 파일로 분리되어 있지 않아 읽기 힘듭니다. 리팩토링을 통해 분리가 필요합니다.

**Comment by Akamig** [comment]
We need more specific countermeasures to mediate this issue, such as specific plan on where we going to separate ipcMain.on() to designated directory structure and files. however we're planning to refactor main.ts in long term, so I'm marking this as stale and closing issue.
