### ISSUE TITLE
Improve ESLint rules and actually use them

### ISSUE THREAD

**Issue by BasixKOR** [planetarium/9c-launcher#1565]
Brutally honestly we haven't really run lint for a very long time and the rules are outdated compared to what we're actually writing. We've met with a couple of production errors that could've been prevented with simple lint (`react-hooks/exhaustive-dep` would prevent 9/10 of those) and it's having a negative impact on the codebase as a whole.

What we need to do:
 - [x] Update rules
   - I'd like to remove airbnb rules since they don't really match what we're actually writing
 - [x] Fix the lint errors
 - [x] Add CI jobs to run them

**Comment by Akamig** [comment]
I think we would agree on a gradual and minimal-to-complicated approach to those rules since lint has been not used for a long time, and there are about 713 problems according to the current ruleset solely on V2 source code. So, what would be a nice starting point?

**Comment by BasixKOR** [comment]
We need to do some evaluations on the known configurations but I think [CRA's default]https://github.com/facebook/create-react-app/tree/master/packages/eslint-config-react-app) looks reasonable.
