### ISSUE TITLE
typescript-resolvers 추가 조사

### ISSUE THREAD

**Issue by moreal** [planetarium/9c-launcher#160]
#113 에서 이어지는 이슈입니다. #124 PR에서 Custom Scalar 타입에 대한 매핑을 추가하였습니다 (e.g., `ByteString` → `ByteStringHex`(=`string`), `Address` → `string`).

덧붙여 `Buffer.from(..., 'hex')` 같은 방법을 통해 `ByteString`에 대한 custom resolver를 붙이기 위해, 추가적으로 조사해보면 좋을 것 같습니다.

PS. javascript graphql 쪽에서 `serialize`, `parseValue`, `parseLiteral` 같은 메소드들을 포함한 `GraphQLScalarType`이 있지만 반환 타입이 다 `any`라서 타입스크립트에서의 이점을 얻을 수 있을지는 의문입니다. 더 조사해봐야 알 것 같습니다.

PR comments
- https://github.com/planetarium/9c-launcher/pull/124#pullrequestreview-443529089
- https://github.com/planetarium/9c-launcher/pull/124#issuecomment-656071667
- https://github.com/planetarium/9c-launcher/pull/124#issuecomment-656093859

**Comment by Akamig** [comment]
Mark as stale, closing.
