### ISSUE TITLE
Webpack is removing necessary files

### ISSUE THREAD

**Issue by Akamig** [planetarium/9c-launcher#1635]
I'm working on it.

**Comment by Akamig** [comment]
I discovered It is actually triggered with `yarn pack-release` and `yarn pack-all` in 171, 183th line of github workflows build.yml.
yarn pack-release = yarn **before-pack** && yarn release
yarn pack all = yarn **before-pack** && yarn run pack
yarn **before-pack** = yarn npm install && yarn build-headless && **yarn bundle-player** && yarn sign-apv

So, why do you think this CI run doesn't include a game executable?

**Comment by Akamig** [comment]
This time I tried to get what downloadPlayer.ts fetches, to check if Ninechronicle's CI is broken. 
but I've got  just completely normal game executable!
https://d3rgdei88xmq6p.cloudfront.net/ab4ef3ce9b8a8de79fc376d58f3ab52b83a59cab/Linux.tar.gz
what is happening here?

**Comment by BasixKOR** [comment]
Well the Windows build uses the same script too and it had no problem, so unless there's something special with Linux/macOS targets I have no clue at the moment.

**Comment by Akamig** [comment]
It was the webpack.config.  during the output clean, keep regex condition was not covering enough, causing some crucial files removed.

**Comment by Akamig** [comment]
![image](https://user-images.githubusercontent.com/6278999/176421450-6e3e12c1-dce7-4bbc-81ce-127f09d99ed8.png)
now it is working as a launcher, but for some reason it fails to load it's assets.
