### ISSUE TITLE
Tab ordering

### ISSUE THREAD

**Issue by sinsangy** [planetarium/9c-launcher#1643]
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/8266625/176654758-5d4d9124-e8fe-47ef-95bf-b628f62345c1.png">

ID -> Password : single tab
Password -> Verify Password : double tab
Verify Password -> Invitation Code : double tab

All of them seem to have to go to the textbox with a single tap.

**Comment by Akamig** [comment]
Actually, there's a visibility button hidden on password fields, which is shown only when hovering and getting focused on the pressing tab. I'll change those are visible on tab focusing instead of removing them. it wouldn't solve "double tap" but at least can see what's focused on explicitly.
