### ISSUE TITLE
Check remaining disk size before updating

### ISSUE THREAD

**Issue by BasixKOR** [planetarium/9c-launcher#1679]
Currently, the launcher tries to update even if the user has not had enough space to download the newer version, which causes the launcher to be stuck on the update screen.

We could check the binary size of the update before downloading and compare the disk size against it, like how we did it with the snapshots.

**Comment by upa-r-upa** [comment]
Hello! May I solve this issue?

**Comment by upa-r-upa** [comment]
I'm sorry for the delay in starting the work. 
working on it right now!!!
