### ISSUE TITLE
Translate FIXME/TODO comments to english

### ISSUE THREAD

**Issue by Akamig** [planetarium/9c-launcher#1686]
![image](https://user-images.githubusercontent.com/6278999/180739369-2de41a49-0465-44af-b81a-a34f3f276a34.png)
![image](https://user-images.githubusercontent.com/6278999/180739405-0f2a218d-6a79-48f7-a850-3f67f52da02d.png)
Whether we're going to deprecate V1 launcher or not, It would be better to get contribution globally if these FIXME/TODO comments are writtern in english. or better, is finding all of these comments and sorting them into issues and finding some GFI from it. What do you think?

**Comment by BasixKOR** [comment]
Awesome idea. Probably a lot of them are outdated so we might need to remove some of it as well (although I'm guessing majority of them would be outdated.)

**Comment by Akamig** [comment]
![image](https://user-images.githubusercontent.com/6278999/180946990-7907d71d-c2ad-446c-8601-5c65cd95bd61.png)
M E T A
