### ISSUE TITLE
Test packager from properly installed XCode Environment

### ISSUE THREAD

**Issue by Akamig** [planetarium/9c-launcher#1702]
## Issue
https://github.com/planetarium/9c-launcher/blob/660efd2343cce4ac7645e9e03987a58acf746622/scripts/packager.js#L1
This packager has been not tested on macOS Environment, due to lack of XCode installation.
We should confirm whether this code is fully functional and able to code signing for macOS.

## Method
Install Xcode on macOS and try to execute this packager.js.

**Comment by BasixKOR** [comment]
Yep, it seems like our credentials are hardcoded into the source code which may need to be fixed
