### ISSUE TITLE
Documentation for Getting Started on the Launcher

### ISSUE THREAD

**Issue by longfin** [planetarium/9c-launcher#1703]
* How to clone (`--recursive`, '`-c core.symlinks true`)
* How to set-up the developer environment for mainnet
* Running yarn codegen
* Checking your modifications - optional?
  * NineChronicles
  * NineChronicles.Headless
  * Lib9c

**Comment by U-lis** [comment]
Start from this, there is a gitbook to archive all 9c document.
[docs.nine-chronicles.com](https://docs.nine-chronicles.com/)
[community docs](https://planetarium.gitbook.io/nine-chronicles-1/)

**Comment by U-lis** [comment]
@BasixKOR After last time you check `getting started` document in github wiki and it's all done in current stage, please close this issue 🙏

**Comment by BasixKOR** [comment]
The [Getting Started](https://github.com/planetarium/9c-launcher/wiki/Getting-Started) docs should be sufficient to get the launcher running now, closing.
