### ISSUE TITLE
Design version scheme for client

### ISSUE THREAD

**Issue by longfin** [planetarium/9c-launcher#1706]

**Comment by Atralupus** [comment]
Add `WindowsPlayerBinaryUrl`, `macOSPlayerBinaryUrl` in apv extra data

**Comment by Atralupus** [comment]
https://{domain}/{rc version}/{project}/{binary}

i.e
https://download.ninechronicles.com/v100270/player/win.zip
https://download.ninechronicles.com/v100270/player/mac.tar.gz
https://download.ninechronicles.com/v100270/launcher/win.zip
https://download.ninechronicles.com/v100270/launcher/mac.tar.gz

**Comment by BasixKOR** [comment]
You may want to consider adding architecture types to the URL as well. You know, future-proofing.

**Comment by Atralupus** [comment]
umm... Player, Headless, etc... can be compatible with multiple rc versions.

https://{domain}/{project}/{project version}/{rc version}/{architecture}

i.e
~/player/v100001/rc100270/win.zip
~/player/v100001/rc100271/arm64
~/launcher/v100003/rc100270/win.zip

**Comment by Atralupus** [comment]
> umm... Player, Headless, etc... can be compatible with multiple rc versions.
> 
> https://{domain}/{project}/{project version}/{rc version}/{architecture}
> 
> i.e ~/player/v100001/rc100270/win.zip ~/player/v100001/rc100271/arm64 ~/launcher/v100003/rc100270/win.zip

It's a bad idea... forget it

**Comment by Atralupus** [comment]
https://{domain}/{rc version}/{project}/{project version}/{architecture}

i.e. ~/v100270/launcher/v1/mac.tar.gz

Then we could delete 'WindowsBinaryUrl', 'macOSBinaryUrl' from apv extra data

**Comment by Atralupus** [comment]
https://{domain}/{env}/{rc version}/{project}/{project version}/{architecture}

i.e. ~/internal/v1085/launcher/v1/mac.tar.gz

for internal, previewnet, etc...
