### ISSUE TITLE
Make settings scrollable

### ISSUE THREAD

**Issue by Akamig** [planetarium/9c-launcher#1726]
As @Atralupus said on #1680, we need additional space to add more features in the Settings page.
thus, making settings scrollable would provide us with enough space to put more elements in there.
Of course, there seem some foreseeable technical difficulties, although.

**Comment by BasixKOR** [comment]
This issue could be done with `overflow: scroll;` or use `@radix-ui/react-scroll-area` if you're feeling fancy :)
