### ISSUE TITLE
Merge Launcher/Player Update State Machine into one

### ISSUE THREAD

**Issue by Akamig** [planetarium/9c-launcher#1779]
## TODO 

- [x] Merge updatePlayerMachine.ts & updateMachine.ts into hierarchical state nodes.
- [ ] Unify Launcher/Player Update Logic (launcherUpdate.ts/playerUpdate.ts)

**Comment by BasixKOR** [comment]
Note that this won't be the final step towards improving the launcher update process. We're aiming to drop the old launcher updater where the launcher itself performs an update (which historically caused numerous problems, including the fact it cannot update the binary itself) and let it be handled by an external updater, which could be our in-house solution or from the Electron community.

**Comment by Akamig** [comment]
Addressed. with #1810.
