### ISSUE TITLE
Provide a shell script for setting up the development environment automatically

### ISSUE THREAD

**Issue by x86chi** [planetarium/9c-launcher#1846]
Having contributed multiple times, I always felt that the process from [cloning](https://github.com/planetarium/9c-launcher/wiki/Getting-Started#3-cloning-repository) to [setting up and running](https://github.com/planetarium/9c-launcher/wiki/Getting-Started#4-build-9c-launcher) was quite cumbersome.

Many Unix-based tools, you automatically install dependencies and configure them to suit your environment. (ex: [On Hy Zsh](https://ohmyz.sh/#install))

```
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
```

It would be nice to have an automation script like this in 9c-launcher.

**Comment by Akamig** [comment]
We have to working on new launcher build process though, almost all process building hard (submodule init, build headless, install dotnet environment, etc) are removed. so I'm marking this issue as resolved.
