### ISSUE TITLE
Launcher has lost the ability to auto-restart the local node

### ISSUE THREAD

**Issue by FioX0** [planetarium/9c-launcher#1847]
Before V280 the launcher had the ability to auto-restart the local node if at any point it would crash.

This was extremely useful due to an issue introduced back in December 2021, where after X time a node would stop being able to execute any actions (couldn't fight or do anything else) despite the chain being up-to-date. So all we had to do was kill headless.exe in TaskManager and it would auto-restart and work again.

This is something my application GQLM also did, every X minutes kill the process. Sadly with V280+ the launcher will no longer restart the node if it is killed.

**Comment by BasixKOR** [comment]
Regression from: https://github.com/planetarium/9c-launcher/commit/3715d76cbe861dec4b7a608b33dc0be7e9c11713

The headless issue isn't something I can fix or take a look at but the restart feature should be fixed.
