### ISSUE TITLE
Add URL to download on ErrorView - Reinstall required.

### ISSUE THREAD

**Issue by Akamig** [planetarium/9c-launcher#1852]
At src/v2/views/ErrorView, line 136, we're just noticing Nine Chronicles should be reinstalled and doing nothing other than restart on this page. more explanation and method to reinstall added would be better.

**Comment by kangjae4real** [comment]
hi

**Comment by BasixKOR** [comment]
The link: https://download.nine-chronicles.com/NineChroniclesInstaller.exe
