### ISSUE TITLE
Staled preload state message

### ISSUE THREAD

**Issue by moreal** [planetarium/9c-launcher#1866]
Currently, Libplanet doesn't support the feature to download states from trusted peers. But it left in libplanet, 9c-headless and 9c-launcher. When the `StateDownloadState` is removed from Libplanet and the 9c-headless applied it, 9c-launcher should also apply it by removing `"Downloading States"` from 
https://github.com/planetarium/9c-launcher/blob/a3b6f4e6c456070e9054d62a6f151710c5e6a47a/src/renderer/views/preload/PreloadProgressView.tsx#L236-L247 and other files.

**Comment by Akamig** [comment]
We no longer use this view, closing.
