### ISSUE TITLE
Create a protocol to deeplink launcher pages

### ISSUE THREAD

**Issue by BasixKOR** [planetarium/9c-launcher#1884]
This semi-RFC proposes a way to open some pages or perform specific actions using `ninechronicles-launcher://` protocol.

Something we have in mind so far:

- `ninechronicles-launcher://open/monster-collection` opens Monster Collection modal and shows it to the user.
- `ninechronicles-launcher://activate?key={invitationCode}` activates an account using the invitation code provided.

**Comment by BasixKOR** [comment]
https://www.electronjs.org/docs/latest/api/app#appsetasdefaultprotocolclientprotocol-path-args

**Comment by BasixKOR** [comment]
Since the protocol name cannot started with number per [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986.html#section-3.1), we need to come up with an alternative

**Comment by Akamig** [comment]
> Since the protocol name cannot started with number per [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986.html#section-3.1), we need to come up with an alternative

I'd suggest `ninechronicles-launcher://`
