### ISSUE TITLE
Detach Headless from Launcher

### ISSUE THREAD

**Issue by BasixKOR** [planetarium/9c-launcher#1913]
Currently, we depends on the headless for these:
- [x] Running the node
- [x] #1914
- [x] #2017 
- [x] Signing the transaction

Although the first one cannot be done inside the launcher, we can implement the rest in the launcher. This issue serves as a tracking issue for decoupling the headless from the launcher.

**Comment by Akamig** [comment]
https://www.notion.so/planetarium/05bd939008f64b1bb92ee92d83b18b12

**Comment by Akamig** [comment]
- [ ] Detach APV Related Headless Code #2017 
- [ ] Detach Keystore Related Headless Code #2033 
- [ ] Detach Action-Tx Related Headless Code 
- [ ] Remove Remain Headless Dependency
- [ ] Remove Headless Git Submodule
- [ ] Functionality Test

**Comment by Akamig** [comment]
끝.
