### ISSUE TITLE
Read the key files without the headless

### ISSUE THREAD

**Issue by BasixKOR** [planetarium/9c-launcher#1914]
We use Web3 Secret Storage as a key file format, which means there are JS implementations we can use instead. 

## Something we found so far
- https://web3js.readthedocs.io/en/v1.7.5/web3-eth-accounts.html

## Concerns
- Possible inconsistency with Libplanet

**Comment by Akamig** [comment]
## Whan We Have Now
- Now we have sphere https://github.com/planetarium/sphere/
- Sphere can 'read keyfile' (account-local)

## Objectives
- Use Sphere's account-local provider instance as Global Keystore
- Implement necessary features in sphere and launcher side each
- Replace `headless/keystore.ts` and `headless/validation.ts`

**Comment by Akamig** [comment]
Done at #2033
