### ISSUE TITLE
Show error screen if the headless crashes

### ISSUE THREAD

**Issue by BasixKOR** [planetarium/9c-launcher#1931]
Currently, when the headless exits for any reason other than explicit action from the user, the launcher attempts to restart the headless regardless of the reason.

This was a quick hack to work around some headless crashes during the game to ensure a smooth gameplay experience, but in cases like failure to run the game from the beginning, it will be stuck in 'Starting Headless', and users would have no idea unless they dig into the log to find out the cause.

The launcher's restart behaviour will now be changed to check the headless's exit code to determine if the error is unrecoverable.

**Comment by Akamig** [comment]
We're working on headless detachment, so marking this issue as closed.
