### ISSUE TITLE
Stop sending `/set-private-key` request

### ISSUE THREAD

**Issue by moreal** [planetarium/9c-launcher#1940]
Currently, NineChronicles.Headless project plans to obsolete `/set-private-key` endpoint completely. So 9c-laucnher should stop to sending `/set-private-key` request automatically.

https://github.com/planetarium/NineChronicles.Headless/discussions/1567

**Comment by BasixKOR** [comment]
Starting place: https://github.com/planetarium/9c-launcher/blob/358bb064f144ef7fbc3f0df9523780a750133f16/src/v2/views/LoginView/index.tsx#L47

**Comment by Akamig** [comment]
Working on https://github.com/planetarium/9c-launcher/tree/fix/remove-mining, including detaching headless.
