### ISSUE TITLE
WNCG Swap not accepting valid ETH address

### ISSUE THREAD

**Issue by Akamig** [planetarium/9c-launcher#2097]
Related with EIP-55 and lowercase I guess?

**Comment by longfin** [comment]
@Akamig Could you leave an address and/or the steps needed to reproduce it?

**Comment by Akamig** [comment]
> @Akamig Could you leave an address and/or the steps needed to reproduce it?

Checked failure case, for example, this user tried Swap
https://9cscan.com/tx/8c2b0cd0d667a562b252981c41e5cda1d6152642f5c3c048c30c2c792bb48c2d

But following ETH address never got any WNCG in return
https://etherscan.io/address/0xcfced09608a0cc6960e063e1afea2dbbcbb1fd6b

**Comment by moreal** [comment]
> Checked failure case, for example, this user tried Swap https://9cscan.com/tx/8c2b0cd0d667a562b252981c41e5cda1d6152642f5c3c048c30c2c792bb48c2d
> 
> But following ETH address never got any WNCG in return https://etherscan.io/address/0xcfced09608a0cc6960e063e1afea2dbbcbb1fd6b

In https://9cscan.com/tx/8c2b0cd0d667a562b252981c41e5cda1d6152642f5c3c048c30c2c792bb48c2d Nine Chronicles tx, it requests to convert  `1547.20` NCG to WNCG. And they are converted in https://etherscan.io/tx/0x40cde4d00634ad40d70eb47f028953c5031196bfe8f11e7c98369577b31b2d66 Ethereum tx. It seems not to have any issues 🤔

----

As a tip, you should use `Erc20 Token Txns` tab to look transactions related with ERC20.

<img width="1287" alt="image" src="https://user-images.githubusercontent.com/26626194/216898745-7070a69a-e0dc-48ff-8db6-804e21524985.png">

**Comment by Akamig** [comment]
It seems to be a simple address case checking logic mismatch between input time and send-button handle time, I fixed it on #2098
