### ISSUE TITLE
Adding the link for source codes to builds

### ISSUE THREAD

**Issue by longfin** [planetarium/9c-launcher#2103]
In order for users receiving the build to access the source code, we should provide the link to GitHub pages (e.g., https://github.com/planetarium/9c-launcher/releases/tag/v100361-2) per release.

**Comment by Akamig** [comment]
1. After https://github.com/planetarium/9c-launcher/pull/2240, we can get commit hash of released source
2. I maintaining https://github.com/planetarium/9c-launcher/releases.
