### ISSUE TITLE
Seperate launcher update flow from 9c release cycle.

### ISSUE THREAD

**Issue by Akamig** [planetarium/9c-launcher#2105]
Extend from #1907.
We need to separate current launcher release cycle from 9c and it's subsidiaries 
since we have no dependency on those project anymore, and this would make update more constantly.
Also, supporting macOS and Linux properly (especially macOS with code signing) is also key issue. which this would be the solution.

---
## Update 2023/03/16

Alright. Here's basic agreement and anticipated workflow from now on. 
Tasks on this TODO list can be seperated into multiple issues, this comment will work as task model.

### Player Updater
- [ ] 9c-player update versioning scheme freeze
- [ ] 9c-player version check / download server API (probably REST) freeze
- [ ] APV version handling logic reform to new 9c-player versioning scheme
- [ ] ....Guess xState update state machine for launcher/player update need to be heavily re-written

### Launcher Updater
- [ ] Windows, macOS launcher signing automation with `electron-updater`
- [ ] Freeze scheme to seperate update channels 
    - Thinking stable (post-QA), beta (pre-QA), alpha (tracking latest `development` branch commit)
- [ ] Applying `electron-updater` as Github Action and manual / automatic tagging?

guess this pretty much sums up the whole job. any ideas to add?

**Comment by Akamig** [comment]
cc @Atralupus.

**Comment by Atralupus** [comment]
We scheduled a discussion about the versioning schema and deployment method, so please wait for this discussion to take place

**Comment by Akamig** [comment]
Aight.

**Comment by Akamig** [comment]
Alright. Here's basic agreement and anticipated workflow from now on. 
Tasks on this TODO list can be seperated into multiple issues, this comment will work as task model.

### Player Updater
- [ ] 9c-player update versioning scheme freeze
- [ ] 9c-player version check / download server API (probably REST) freeze
- [ ] APV version handling logic reform to new 9c-player versioning scheme
- [ ] ....Guess xState update state machine for launcher/player update need to be heavily re-written

### Launcher Updater
- [ ] Windows, macOS launcher signing automation with `electron-updater`
- [ ] Freeze scheme to seperate update channels 
    - Thinking stable (post-QA), beta (pre-QA), alpha (tracking latest `development` branch commit)
- [ ] Applying `electron-updater` as Github Action and manual / automatic tagging?

guess this pretty much sums up the whole job. any ideas to add?

**Comment by Atralupus** [comment]
We supply version information to accommodate various providers:
- For the launcher, it is obtained from the GitHub release.
- For the player, it is sourced from https://release.nine-chronicles.com/player-version.json

Regarding the player, the launcher will implement polling of the aforementioned JSON file.
