### ISSUE TITLE
Print Current Launcher Version in Settings Overlay

### ISSUE THREAD

**Issue by Akamig** [planetarium/9c-launcher#2236]
I think it would be nice to acknowledge what version of launcher is running from user interface, 

- Helps backtracking issue at the certain point of time (between versions)
- Easily distinguishable if update condition is properly met or not,
- Confirms which launcher currently installed (internal and main-net)

**Comment by nvsai** [comment]
Hi @Akamig I would like to try this issue could you please assign me?

**Comment by Akamig** [comment]
@nvsai 
OH YES
THANKS
WELCOME
MUCH APPRECIATED

You can create fork, or branch from current `development` branch and work from there!
As saying "version", it's semver from package.json. (currently 2.1.1)
you don't have to adjust that to 2.1.2 after your contribution, but anyway.

If you have any problem while working, ask anything to me!

**Comment by nvsai** [comment]
Hi @Akamig Thank you for assigning me this issue.
![Screenshot from 2023-07-18 11-08-45](https://github.com/planetarium/9c-launcher/assets/65706186/add31f61-fad0-45ca-b8f1-9e17eb494aa1)

I have placed the version in left bottom.And i have made changes in webpack.config to export version from package.json.Please let me know if any changes are required.

**Comment by Akamig** [comment]
@nvsai 
Oh, no. Everything is perfect! "click-to-paste" is also nice touch!
Thanks for your contribution. 
Create PR, then I'll review your fix very quickly.

**Comment by nvsai** [comment]
@AkamigI have created the PR.This would be my first open source contribution for a project of this scale Thank you very much.
