### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by earlbread** [planetarium/9c-launcher#232]
```
Cannot read property 'toString' of undefined
```

https://sentry.io/organizations/planetariumhq/issues/1824435582/?project=5289089&query=is%3Aunresolved&statsPeriod=7d

Quit 할때 발생하는것으로 보이고 `pid`가 `undefined`인것 같습니다.

**Comment by Akamig** [comment]
Marking as stale, close issue.
