### ISSUE TITLE
Error: spawn C:\Users\hdave\AppData\Local\Programs\Nine Chronicles\resources\app\9c.exe ENOENT

### ISSUE THREAD

**Issue by earlbread** [planetarium/9c-launcher#237]
`9c.exe` 외에  `NineChronicles.Standalone.Executable`가 없는 경우도 있는 것 같습니다.
https://sentry.io/organizations/planetariumhq/issues/1751881984/?project=5289089&query=is%3Aunresolved&statsPeriod=7d

**Comment by Akamig** [comment]
Marking as stale, close issue.
