### ISSUE TITLE
Fatal Error: EXC_BAD_ACCESS / KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by earlbread** [planetarium/9c-launcher#239]
Invalid address access 같은 kernel exception으로 죽는 경우가 있는 것 같습니다.

https://sentry.io/organizations/planetariumhq/issues/1834155664/?project=5289089&query=is%3Aunresolved&statsPeriod=7d

https://sentry.io/organizations/planetariumhq/issues/1831911968/?project=5289089&query=is%3Aunresolved&statsPeriod=7d

https://sentry.io/organizations/planetariumhq/issues/1831526486/?project=5289089&query=is%3Aunresolved&statsPeriod=7d

https://sentry.io/organizations/planetariumhq/issues/1823265063/?project=5289089&query=is%3Aunresolved&statsPeriod=7d

https://sentry.io/organizations/planetariumhq/issues/1780006886/?project=5289089&query=is%3Aunresolved&statsPeriod=7d

**Comment by Akamig** [comment]
Marking as stale, close issue.
