### ISSUE TITLE
Replace the installer

### ISSUE THREAD

**Issue by riemannulus** [planetarium/9c-launcher#244]
Due to historical reasons, the installer currently resides in the [NineChronicles](https://github.com/planetarium/NineChronicles/tree/master/tools). We want to replace this with an NSIS-based installer, preferably built with [electron-builder](https://www.electron.build/).

**Comment by Akamig** [comment]
@Atralupus did it after painstaking CI improvement. closing.
https://github.com/planetarium/9c-launcher/pull/2142
