### ISSUE TITLE
Merge ForgotPasswordView and ImportView into single view component

### ISSUE THREAD

**Issue by Akamig** [planetarium/9c-launcher#2483]
Related to #2249.
In view components of Renderer, "[ForgotPasswordView](https://github.com/planetarium/9c-launcher/blob/e9a1b1468160e67479b28bd8ffbac954409efe30/src/renderer/views/ForgotPasswordView/index.tsx)" and "[ImportView](https://github.com/planetarium/9c-launcher/blob/e9a1b1468160e67479b28bd8ffbac954409efe30/src/renderer/views/ImportView/index.tsx#L18)" has Identical structure, and this causes duplicated commits when maintaining these Views.

So, if possible I hope to merge these two views into single view component and adjust router to share this view.

**Comment by Hoogokok** [comment]
해보겠습니다.
