### ISSUE TITLE
MacOS에서 권한 문제로 인해 앱이 제대로 실행되지 않는 경우

### ISSUE THREAD

**Issue by riemannulus** [planetarium/9c-launcher#265]
#214 에서 발생한 문제입니다.

스토어 저장소 위치를 `planetarium/` 밑으로 옮기면서 MacOS에서 권한 문제가 발생하여 블록을 받아올 수가 없어 론처가 제대로 실행되지 않습니다.
MacOS관련 문제이지만, #230 관련해서 저장소 위치를 config.json으로 완전히 이관하자는 말이 있어 같이 해결하면 좋을 것 같습니다.
https://www.notion.so/planetarium/2020-08-18-cf0ea7a5ed06485b80a249a082ca1d0f

**Comment by Akamig** [comment]
It somewhat resolved now, and marking this as stale. closing issue.
