### ISSUE TITLE
네트워크의 제네시스 블록이 바뀌었을때의 처리

### ISSUE THREAD

**Issue by longfin** [planetarium/9c-launcher#308]
`config.json`의 `PeerString`에 정의된 노드로 처음 접속하게 되는데, 이때 해당 노드가 가지고 있는 제네시스 블록의 해시가 내가 가지고 있는 것과 다르면, 데이터 삭제 후 재시작 안내가 출력됩니다. 하지만 테스트넷의 체인 리셋에서는 해당 안내대로 진행해도 이전 버전의 스냅샷을 받은 후 다시 실패합니다.

네트워크의 제네시스 블록이 내가 알던 것과 다를 때, 이를 자연스럽게 마이그레이션 할 수 있게끔 처리가 필요합니다.

**Comment by Akamig** [comment]
현재는 런쳐에서 스냅샷을 받고 있지 않기도 하고, 제네시스 블럭을 웹에서 받아오는 관계로 메인넷 / 인터널 체제에서는 일어나기 어려운 케이스로 보여져, 이슈를 닫습니다.
