### ISSUE TITLE
Manage localization script with a spreadsheet

### ISSUE THREAD

**Issue by x86chi** [planetarium/9c-launcher#411]
> [Nine Chronicles Translation Project](https://docs.google.com/spreadsheets/d/1_e8T3NSW5NS43j5Aa-U9pwckD0xx0ahzkoDmOmG0H_8/edit#gid=159327328)

## Goal

Converting CSV data to JSON format.

**Comment by x86chi** [comment]
Need to contribute? :eyes:

**Comment by Akamig** [comment]
We're using transifex as i18n management, so closing this issue.
