### ISSUE TITLE
GraphQL webpack intergration

### ISSUE THREAD

**Issue by moreal** [planetarium/9c-launcher#43]
#41 이후 graphql-code-generator가 적용되었습니다.
하지만 직접 CLI에서 호출하게 하였기 때문에 webpack에서 제공하는 hot-reload 기능을 사용하지 않습니다.
graphql-code-generator에도 hot-reload를 적용할 수 있으면 좋겠습니다.

https://github.com/dotansimha/graphql-code-generator/discussions/3494

**Comment by Akamig** [comment]
marking as stale issue, closing.
