### ISSUE TITLE
ErrorReinstallView 내용 수정

### ISSUE THREAD

**Issue by limebell** [planetarium/9c-launcher#508]
현재는 재설치를 안내해야 하는 `ErrorReinstallView` 페이지에서 클리어 캐시를 요구하고 있습니다. `ErrorClearCacheView` 페이지가 새로 추가되었기에 해당 페이지에서 안내해야 하는 내용을 바꾸어야 합니다.

**Comment by Akamig** [comment]
We resolved this issue on V2 launcher, and V1 is going to be deprecated at the moment, so closing this issue
