### ISSUE TITLE
Module not found (spawn-sync, utf-8-validate, bufferutil)

### ISSUE THREAD

**Issue by AkiaCode** [planetarium/9c-launcher#565]
![image](https://user-images.githubusercontent.com/71239005/110406536-bc3da000-80c5-11eb-83d7-d61fb276878c.png)

**Comment by longfin** [comment]
Thanks for reporting, we'll investigate. (PR is also welcome 😅)

**Comment by AkiaCode** [comment]
매우 간단한 해결방법은 `npm i spawn-sync utf-8-validate bufferutil` 하면 끝납니다

**Comment by BasixKOR** [comment]
Fixed by #789.
