### ISSUE TITLE
Authentication session error

### ISSUE THREAD

**Issue by moreal** [planetarium/9c-launcher#645]
Now, it doesn't send session cookies to GraphQL endpoint well. It causes authentication error.

## How to verify this issue resolved

 1. Create a new private key with invitation key after removing all keys in key-store.
 1. Log in and wait until preloading ended.
 1. Check `POST /graphql` activation GraphQL query request passed successfully without unauthorized error or CORS error, through `Developer Tools > Network` tab or other tool.

For more description, mention @moreal, @boscohyun.

## References

 - https://developer.mozilla.org/en-US/docs/Web/API/Request/mode

**Comment by Akamig** [comment]
This is not happening in current launcher, closing.
