### ISSUE TITLE
Parallelize state / tx snapshot downloading

### ISSUE THREAD

**Issue by longfin** [planetarium/9c-launcher#651]

**Comment by area363** [comment]
I'm closing this issue because the parallel download did not show any improvement in local testing. 😢 

< **Local Test Data** >

**Serial Download** (avg: 2:49)
1. 2:53
2. 2:43
3. 2:44
4. 3:00
5. 2:53
6. 2:46

**Parallel Download** (avg: 2:52)
1. 2:50
2. 3:00
3. 2:53
4. 2:43
5. 3:01
6. 2:50
