### ISSUE TITLE
Can't download snapshot

### ISSUE THREAD

**Issue by PoohVz** [planetarium/9c-launcher#706]
This issue happens mostly for new players or people who cleared cache and the game starts to download snapshot again.
![image](https://user-images.githubusercontent.com/13524523/119247979-30152200-bbb8-11eb-88d2-ebc459995cb5.png)

Some people fix the issue by running the launcher by admin, or keep trying after a few times.

Logs:
[main(1).log](https://github.com/planetarium/9c-launcher/files/6527587/main.1.log)

**Comment by area363** [comment]
We've found this issue to occur when there are `too many partitioned snapshot files` to download. We've recently reset the number of partitioned snapshots so this issue should be resolved for now.

Note) `Resetting snapshot file count` should be done periodically to prevent this issue from reoccurring @planetarium/9c-backend.

Thanks for your report! @PoohVz
