### ISSUE TITLE
The Root chain store path keeps resetting whenever there is a new update

### ISSUE THREAD

**Issue by PoohVz** [planetarium/9c-launcher#776]
It would be nice if the said setting stays the same after the new update
![image](https://user-images.githubusercontent.com/13524523/123005806-ea2ec200-d3e0-11eb-8a49-0df06c84dbeb.png)

**Comment by BasixKOR** [comment]
Adressed by #823.

**Comment by longfin** [comment]
Thanks for the suggestion. after #823, we have a per-user config for overriding.
