### ISSUE TITLE
In rare cases, already activated account is requested to activate again

### ISSUE THREAD

**Issue by dahlia** [planetarium/9c-launcher#801]
According to @Namyujeong, this kind of problems have been reported several times, so I report it as an issue here.

<https://discord.com/channels/539405872346955788/582156664283594753/861966087330332673>:

> **taco**: I started playing yesterday and made decent progress. Today I logged in and it's asking for an invitation code again. Do I need a new invitation code every time I start the game? Have I somehow lost my progress from yesterday? I'm nervous about putting a new code in.

<https://discord.com/channels/539405872346955788/582156664283594753/861966317174784000>:

> @PoohVz: restart your launcher and try again, activation code is 1 time thing

<https://discord.com/channels/539405872346955788/582156664283594753/861966606602076161>:

> **taco**: hi @PoohVz I've relaunched a few times. I log in with my password but has asked for a new activation code each time.

<https://discord.com/channels/539405872346955788/582156664283594753/861966693353259008>:

> @PoohVz: try clearing cache
>
> @PoohVz: it's in the launcher setting

<https://discord.com/channels/539405872346955788/582156664283594753/861970234474364948>:

> **taco**: @PoohVz I cleared the cache and after everything reloaded it still asks for a new activation code. weird.

<https://discord.com/channels/539405872346955788/582156664283594753/861970446575206410>:

> @PoohVz: hmm @limebell @dahlia can you help this one
>
> @PoohVz: his game keeps asking for code, he activated before
>
> @PoohVz: cleared cache doesn't work

<https://discord.com/channels/539405872346955788/582156664283594753/861977258343268352>:

> @dahlia: Let me know your address?

<https://discord.com/channels/539405872346955788/582156664283594753/861980468420018176>:

> **taco**:
> ```
> APV: 100054/6ec8E598962F1f475504F82fD5bF3410eAE58B9B/MEQCIALIs29zklIK2N5oSduMipOOx9.SpZioBUi60+oihJQpAiAXGvx3y2q7UPj37CBGFXF9VouIX5rU4VhxX74zn6JN4A==/ZHUxNjpXaW5kb3dzQmluYXJ5VXJsdTU2Omh0dHBzOi8vZG93bmxvYWQubmluZS1jaHJvbmljbGVzLmNvbS92MTAwMDU0L1dpbmRvd3MuemlwdTk6dGltZXN0YW1wdTEwOjIwMjEtMDYtMjll 
> Address: 0x4bA4b9739526AF40118A08f6552b48dC87Bd5631 
> Debug: false / false
> Mined blocks: undefined (out of recent 500 blocks)
> Client ID: 7d6e270f-527c-41ed-a91b-578c133c9c5b
> ```

<https://discord.com/channels/539405872346955788/582156664283594753/861995213856440320>:

> @dahlia: Sorry for my late response.  I've investigated and found the transaction you activated the account (`46356c82d3e99825c394ca16243720c47b9b74b3c678fed00afb94a3c10bb6b4`).  In other words, on the blockchain, your account is already activated.  It's still unsure why you still see the activation page… It could be a bug, and I'll report this to our bug tracker.

**Comment by BasixKOR** [comment]
It should be fixed by now. Please open the issue again if this persists.
