### ISSUE TITLE
Output built with `yarn run pack` does not run.

### ISSUE THREAD

**Issue by longfin** [planetarium/9c-launcher#822]
# Enviornment
- https://github.com/planetarium/9c-launcher/commit/8838a30d0594d5b6e2c32f0b557965e1458ffd94
- Windows 10 pro
```
PS C:\Users\X1E\electron-launcher> node --version
v16.0.0
PS C:\Users\X1E\electron-launcher> yarn --version
1.22.5
```

# Step to reproduce
```
PS C:\Users\X1E\electron-launcher> yarn run pack
PS C:\Users\X1E\electron-launcher> & '.\pack\Nine Chronicles-win32-x64\Nine Chronicles.exe'
```

# Expected result
`Nine Chronicles.exe` runs without errors.

# Actual result
![image](https://user-images.githubusercontent.com/128436/125727745-eb800890-0261-4ae7-85a8-f9da86e58934.png)

It gives the same error as above and does not display any UI.

**Comment by BasixKOR** [comment]
It seems like it's caused by using `nodeExternals` in main.

**Comment by longfin** [comment]
@BasixKOR It has still broken on b26122ced4c9737b6e64a414c23bcb3fcd9527df.

**Comment by BasixKOR** [comment]
@longfin Yeah, that commit doesn't resolve this bug. Please see #826 for that matter.
