### ISSUE TITLE
Confirm clear cache action by typing words

### ISSUE THREAD

**Issue by dahlia** [planetarium/9c-launcher#985]
Currently the *Clear cache* button is simply confirmed by only clicking the *OK* button:

![The current clear cache confirmation dialog](https://user-images.githubusercontent.com/12431/137241920-173ed08d-4713-4787-9051-77c2777b3666.png)

However, the clear cache action is getting more expensive than early days, so it should be warned in a stronger manner.  I suggest to change the confirmation dialog to ask a user to type words like *yes* (or any other arbitrary words) instead of showing the *OK* button:

![How GitHub confirms dangerous action](https://user-images.githubusercontent.com/12431/137242439-a81f5ad5-a21b-4287-b307-0fb5a5da6a3c.png)

**Comment by BasixKOR** [comment]
Shoud we put this in v100082? The description of the confirmation dialogue has been changed, but currently, it just shows Yes/No buttons.
